# otp_service.py

import random
from twilio.rest import Client

# Your Twilio Account SID, Auth Token, and Twilio Phone Number
# IMPORTANT: Replace these placeholders with your actual Twilio credentials.
TWILIO_ACCOUNT_SID = '' # Your Twilio Account SID
TWILIO_AUTH_TOKEN = ''  # Your Twilio Auth Token
TWILIO_PHONE_NUMBER = '+14437323022' # Your Twilio phone number (e.g., from Twilio dashboard)


def generate_otp():
    """
    Generates a random 4-digit OTP.
    Returns:
        int: A random 4-digit integer.
    """
    return random.randint(1000, 9999)

def verify_otp(user_input_otp, generated_otp):
    """
    Verifies if the user-entered OTP matches the generated OTP.
    Args:
        user_input_otp (int): The OTP entered by the user.
        generated_otp (int): The OTP generated by the system.
    Returns:
        bool: True if OTPs match, False otherwise.
    """
    return user_input_otp == generated_otp
